### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by kuangdai** [SeismicData/asdf_sextant#5]
Hi Lion,

The GUI does not work unless I comment out the following lines in main.py:

if station not in info["ds"].waveforms:
          continue

The condition is always true

Cheers,
Kuangdai

**Comment by krischer** [comment]
Ah yea - the sextant currently only works with the latest pyasdf master - I'll cut a new pyasdf release that should fix it soon.

**Comment by krischer** [comment]
thanks for reporting.

**Comment by krischer** [comment]
Already fixes a couple of weeks ago.
